name: Docs test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  docs-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.3/pandoc-3.3-1-amd64.deb
          sudo dpkg -i pandoc-3.3-1-amd64.deb

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          pip install -e .[dev,docs,notebooks]

      - name: Run tests
        run: |
          pytest vespa --doctest-modules

      - name: Run linkcheck
        run: |
          sphinx-build -E -b linkcheck docs/sphinx/source docs/sphinx/build
          sphinx-build -E docs/sphinx/source docs/sphinx/build
          rm -fr docs/sphinx/build

