name: Integration - except cloud

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  integration-except-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Run integration docker
        run: |
          pytest tests/integration/test_integration_docker.py -s -v
